#!/bin/sh
#
# 根据 commitmsg 以及 branch name 判断是否需要 commitlint
#
# Author: waiting
# Date: 2019.01.20
#

branch=$( git branch | grep \* | cut -d ' ' -f2 )
#node ./.githooks/is-skip-commitlint.js $1 "$branch"
ts-node -P tsconfig.cjs.json ./.githooks/is-skip-commitlint.ts $1 "$branch"

code=$?
#echo -e 'node exitCode:' $code

if [[ $code = 0 ]] ; then
  commitlint -e
fi

