extends: '@waiting/eslint-config'
parserOptions:
  project: 'tsconfig.eslint.json'

# https://eslint.org/docs/rules/
# https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
# https://github.com/benmosher/eslint-plugin-import
# https://github.com/sindresorhus/eslint-plugin-unicorn
rules:
  # Use tsconfig.json noUnusedLocals:true instead
  "@typescript-eslint/no-unused-vars": 0
  "node/no-unpublished-import": 0
  "@typescript-eslint/prefer-ts-expect-error": 0
  "unicorn/filename-case": 0
  "linebreak-style": 0
  "node/shebang": 0

